
services:
      app:
        build:
          context: .
          args: 
            - DEV=true
          dockerfile: Dockerfile
        command: >
              sh -c "python manage.py runserver 0.0.0.0:8000"
        volumes:
            - ./app:/app
        ports:
            - "8000:8000"
        env_file:
            - .env
        depends_on:
            - db

      db:
        image: postgres:16.5-alpine
        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes: 
            - dev-db-django:/var/lib/postgresql/data

volumes:
  dev-db-django:
